_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
  STEPS: (69600, 92800)
  MAX_ITER: 116000
  WARMUP_ITERS: 3625
TEST:
  EVAL_PERIOD: 29000
VIS_PERIOD: 2320
DATASETS:
  TRAIN: ('KITTI_train', 'KITTI_val')
  TEST: ('KITTI_test',)
  CATEGORY_NAMES: ('cyclist', 'pedestrian', 'trailer', 'bus', 'motorcycle', 'car', 'barrier', 'truck', 'van', 'traffic cone', 'bicycle')
  # CATEGORY_NAMES: ('cyclist', 'pedestrian', 'car')
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 11