_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 4
  BASE_LR: 0.0025
  STEPS: (3340800, 4454400)
  MAX_ITER: 5568000
  WARMUP_ITERS: 174000
TEST:
  EVAL_PERIOD: 1392000
VIS_PERIOD: 111360
DATASETS:
  TRAIN: ('KITTI_train', 'KITTI_val')
  TEST: ('KITTI_test',)
  CATEGORY_NAMES: ('cyclist', 'pedestrian', 'trailer', 'bus', 'motorcycle', 'car', 'barrier', 'truck', 'van', 'traffic cone', 'bicycle')
  # CATEGORY_NAMES: ('cyclist', 'pedestrian', 'car')
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 11